"""Friendly interactive setup wizard.

Run after installing the package:  ha-mcp-setup

It walks a non-technical user through:
  1. Entering their Home Assistant address + access token (opens the token page).
  2. Testing the connection.
  3. Optionally enabling raw YAML file access over SSH.
  4. Writing .env and .mcp.json.
  5. Registering the server with the Claude Code CLI (if installed).
  6. Optionally creating the 'Claude Link' dashboard automatically.
"""

from __future__ import annotations

import asyncio
import json
import shutil
import subprocess
import sys
import webbrowser
from pathlib import Path

from .config import Settings
from .dashboard_template import build_dashboard
from .ha_client import HAClient


def _ask(prompt: str, default: str | None = None) -> str:
    suffix = f" [{default}]" if default else ""
    value = input(f"{prompt}{suffix}: ").strip()
    return value or (default or "")


def _ask_yes(prompt: str, default: bool = True) -> bool:
    d = "J/n" if default else "j/N"
    value = input(f"{prompt} ({d}): ").strip().lower()
    if not value:
        return default
    return value in {"j", "ja", "y", "yes"}


def _is_local(url: str) -> bool:
    host = url.split("//")[-1].split("/")[0].split(":")[0].lower()
    return (
        host in {"localhost", "127.0.0.1"}
        or host.endswith(".local")
        or host.startswith(("192.168.", "10.", "172.16.", "172.17.", "172.18."))
    )


def _secure(path: Path) -> None:
    """Restrict a secrets file to the current user (best effort, no-op on Windows)."""
    try:
        path.chmod(0o600)
    except (OSError, NotImplementedError):
        pass


def _make_settings(values: dict) -> Settings:
    return Settings(
        ha_url=values["HA_URL"],
        ha_token=values["HA_TOKEN"],
        verify_ssl=values.get("HA_VERIFY_SSL", "true").lower() != "false",
        timeout=30.0,
        files_backend=values.get("HA_FILES_BACKEND", "none"),
        config_dir=values.get("HA_CONFIG_DIR"),
        ssh_host=values.get("HA_SSH_HOST"),
        ssh_port=int(values.get("HA_SSH_PORT", "22")),
        ssh_user=values.get("HA_SSH_USER"),
        ssh_password=values.get("HA_SSH_PASSWORD"),
        ssh_key_file=values.get("HA_SSH_KEY_FILE"),
        ssh_config_dir=values.get("HA_SSH_CONFIG_DIR", "/config"),
        read_only=values.get("HA_READ_ONLY", "false").lower() == "true",
        snapshots_enabled=values.get("HA_SNAPSHOTS", "true").lower() != "false",
        snapshot_dir=values.get("HA_SNAPSHOT_DIR", str(Path.home() / ".ha-mcp" / "snapshots")),
        auto_backup_before_update=values.get("HA_AUTO_BACKUP_BEFORE_UPDATE", "false").lower() == "true",
    )


async def _test_connection(settings: Settings) -> dict:
    client = HAClient(settings)
    try:
        return await client.rest_get("/config")
    finally:
        await client.aclose()


async def _create_dashboard(settings: Settings) -> None:
    client = HAClient(settings)
    try:
        existing = await client.ws_command({"type": "lovelace/dashboards/list"})
        if not any(d.get("url_path") == "claude-link" for d in existing):
            await client.ws_command(
                {
                    "type": "lovelace/dashboards/create",
                    "title": "Claude Link",
                    "url_path": "claude-link",
                    "icon": "mdi:robot-happy",
                    "show_in_sidebar": True,
                    "mode": "storage",
                }
            )
        await client.ws_command(
            {
                "type": "lovelace/config/save",
                "url_path": "claude-link",
                "config": build_dashboard(),
            }
        )
    finally:
        await client.aclose()


async def _make_backup(settings) -> None:
    client = HAClient(settings)
    try:
        await client.rest_post("/hassio/backups/new/full", {"name": "Voor Claude Code"})
    finally:
        await client.aclose()


def _write_env(values: dict, path: Path) -> None:
    lines = ["# Generated by ha-mcp-setup", ""]
    for key in (
        "HA_URL", "HA_TOKEN", "HA_VERIFY_SSL", "HA_FILES_BACKEND",
        "HA_CONFIG_DIR", "HA_SSH_HOST", "HA_SSH_PORT", "HA_SSH_USER",
        "HA_SSH_PASSWORD", "HA_SSH_KEY_FILE", "HA_SSH_CONFIG_DIR",
        "HA_READ_ONLY", "HA_SNAPSHOTS", "HA_AUTO_BACKUP_BEFORE_UPDATE",
    ):
        if values.get(key):
            lines.append(f"{key}={values[key]}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_mcp_json(values: dict, command: str, path: Path) -> None:
    env = {k: v for k, v in values.items() if v}
    config = {"mcpServers": {"home-assistant": {"command": command, "env": env}}}
    if path.exists():
        try:
            existing = json.loads(path.read_text(encoding="utf-8"))
            existing.setdefault("mcpServers", {})["home-assistant"] = config["mcpServers"]["home-assistant"]
            config = existing
        except (json.JSONDecodeError, OSError):
            pass
    path.write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")


def _register_with_claude(values: dict, command: str) -> bool:
    claude = shutil.which("claude")
    if not claude:
        return False
    args = [claude, "mcp", "add", "home-assistant"]
    for key, val in values.items():
        if val:
            args += ["--env", f"{key}={val}"]
    args += ["--", command]
    try:
        subprocess.run(args, check=True)
        return True
    except (subprocess.CalledProcessError, OSError):
        return False


def main() -> None:
    print("\n=== Home Assistant ↔ Claude Code setup ===\n")
    values: dict = {}

    # 1. Address + token
    values["HA_URL"] = _ask("Webadres van Home Assistant", "http://homeassistant.local:8123")
    print("\nIk open nu de pagina waar je een token kunt aanmaken.")
    print("Klik onderaan op 'Token aanmaken', geef het de naam 'claude-code' en kopieer het.")
    try:
        webbrowser.open(values["HA_URL"].rstrip("/") + "/profile/security")
    except Exception:
        pass
    values["HA_TOKEN"] = _ask("\nPlak hier je token")
    if values["HA_URL"].startswith("https://") and not _ask_yes(
        "Gebruik je een geldig (niet zelf-ondertekend) certificaat?", True
    ):
        values["HA_VERIFY_SSL"] = "false"
    elif values["HA_URL"].startswith("http://") and not _is_local(values["HA_URL"]):
        print("\n⚠️  Beveiligingstip: je gebruikt een onversleutelde (http) verbinding")
        print("    naar een adres buiten je eigen netwerk. Je token reist dan onbeschermd.")
        print("    Gebruik bij voorkeur een https-adres (bijv. via Nabu Casa of een reverse proxy).")

    # 2. Test
    print("\nVerbinding testen...")
    try:
        info = asyncio.run(_test_connection(_make_settings(values)))
        print(f"✅ Verbonden met Home Assistant {info.get('version')} ({info.get('location_name')}).")
    except Exception as exc:  # noqa: BLE001
        print(f"❌ Kon geen verbinding maken: {exc}")
        print("Controleer het adres en token en probeer opnieuw.")
        sys.exit(1)

    # 3. File access
    if _ask_yes("\nWil je dat Claude ook YAML-bestanden kan bewerken (aanrader)?", True):
        print("Hiervoor gebruik je de 'Advanced SSH & Web Terminal' add-on in Home Assistant.")
        values["HA_FILES_BACKEND"] = "ssh"
        values["HA_SSH_HOST"] = _ask("SSH-adres", values["HA_URL"].split("//")[-1].split(":")[0])
        values["HA_SSH_PORT"] = _ask("SSH-poort", "22")
        values["HA_SSH_USER"] = _ask("SSH-gebruiker", "root")
        if _ask_yes("Inloggen met een SSH-sleutel i.p.v. wachtwoord (veiliger)?", False):
            values["HA_SSH_KEY_FILE"] = _ask("Pad naar je private key", str(Path.home() / ".ssh" / "id_ed25519"))
        else:
            values["HA_SSH_PASSWORD"] = _ask("SSH-wachtwoord (van de add-on)")
        values["HA_SSH_CONFIG_DIR"] = "/config"
        # Snapshots make file edits reversible; keep them on by default.
        values["HA_SNAPSHOTS"] = "true"
    else:
        values["HA_FILES_BACKEND"] = "none"

    # 3b. Safety choices
    if _ask_yes("\nVeilige modus aanzetten (Claude mag alles LEZEN maar niets WIJZIGEN)?", False):
        values["HA_READ_ONLY"] = "true"
        print("   → Veilige modus AAN. Zet later HA_READ_ONLY=false om wijzigingen toe te staan.")
    if _ask_yes("Automatisch een back-up maken vóór elke update (aanrader)?", True):
        values["HA_AUTO_BACKUP_BEFORE_UPDATE"] = "true"

    # 4. Write config files (with restrictive permissions on secrets)
    cwd = Path.cwd()
    env_path = cwd / ".env"
    mcp_path = cwd / ".mcp.json"
    _write_env(values, env_path)
    command = shutil.which("ha-mcp") or str(Path(sys.executable).with_name("ha-mcp"))
    _write_mcp_json(values, command, mcp_path)
    _secure(env_path)
    _secure(mcp_path)
    print(f"\n✅ Configuratie opgeslagen (alleen voor jou leesbaar) in {env_path} en {mcp_path}.")

    # 5. Register with Claude Code CLI
    if _register_with_claude(values, command):
        print("✅ Server toegevoegd aan Claude Code (claude mcp add).")
    else:
        print("ℹ️  Claude Code CLI niet gevonden — gebruik het .mcp.json bestand in je project.")

    # 6. Dashboard
    if _ask_yes("\nWil je het 'Claude Link' dashboard automatisch aanmaken in Home Assistant?", True):
        try:
            asyncio.run(_create_dashboard(_make_settings(values)))
            print("✅ Dashboard 'Claude Link' aangemaakt (zie de zijbalk in Home Assistant).")
        except Exception as exc:  # noqa: BLE001
            print(f"⚠️  Kon het dashboard niet aanmaken: {exc}")

    # 7. Optional baseline backup (safety net before you start changing things)
    if _ask_yes("\nWil je nu meteen een back-up van Home Assistant maken als veilig startpunt?", True):
        try:
            asyncio.run(_make_backup(_make_settings(values)))
            print("✅ Back-up gestart in Home Assistant (Instellingen → Systeem → Back-ups).")
        except Exception as exc:  # noqa: BLE001
            print(f"⚠️  Kon geen back-up maken (alleen op HA OS/Supervised): {exc}")

    print("\nKlaar! 🎉")
    print("Tip: installeer ook de 'Claude Link' integratie via HACS voor de status-tegels.")
    print("Herstart daarna Claude Code en typ /mcp om te controleren of 'home-assistant' verbonden is.\n")


if __name__ == "__main__":
    main()
